neuroinformatics-unit/python-cookiecutter

.pre-commit-config.yaml, README.md, pyproject.toml, tests/test_cookiecutter.py, {{cookiecutter.package_name}}/.pre-commit-config.yaml, {{cookiecutter.package_name}}/pyproject.toml
This replaces `isort` with `ruff`, by adding the "I" rule explicitly. I also turned out autofix, so running `pre-commit` will make fixes for you in some cases where `ruff` complains (including sorting imports).
=> Replace isort with ruff

pyproject.toml, {{cookiecutter.package_name}}/pyproject.toml
[`black` automatically ignores files already specified in `.gitignore`](https://black.readthedocs.io/en/stable/usage_and_configuration/file_collection_and_discovery.html#gitignore), so remove files that are duplicated across `.gitignore` and the black config.
The remaining entries were
```toml
exclude = '''
(
/(
| _build
| buck-out
| examples
)/
)
'''
```
and I these should either be in `.gitignore` (`_build`), not be ignored by black (`examples`) or I don't know what they are (`buck-out`), so I've just removed the exclude config completely.
=> Remove black excludes config

{{cookiecutter.package_name}}/pyproject.toml
This adds `cibuildwheel` configuration, in particular to:
- Limit Python versions that are being used to those that are used for testing
- Build wheels for macOS arm64, which needs to be manually specified.
=> Add cibuildwheel config

tests/test_cookiecutter.py
This cleans up the test, with the following goals:
- Move the tests into individual `test_` functions, instead of running them at the bottom of the file.
- Use pytest fixtures to setup the package in a temporary directory, and then pip install the package.
- Use a pytest fixture that yields to automatically pip uninstall the package once testing is finished.
This ended up being a bit of a re-write - sorry for the large diff! But this should make it a lot easier to extend the tests in the future. If anything doesn't make sense please let me know!
=> Test rewrite

tests/test_cookiecutter.py, {{cookiecutter.package_name}}/pyproject.toml
The formatting of PyPI links in `datashuttle` was inherited from here.
I applied the same update as in https://github.com/neuroinformatics-unit/datashuttle/pull/168
=> Update PyPI link names

{{cookiecutter.package_name}}/.pre-commit-config.yaml, {{cookiecutter.package_name}}/MANIFEST.in
Just realised that as soon as someone makes a new package using the cookiecutter, they'll run into problems with `check-manifest` complaining. So I added some extra exclusions to `MANIFEST.in`. 
I also added a `check-manifest` pre-commit hook, which will be run after all the other hooks. This way users will be able to catch the annoying manifest errors before the push, and not after (as it currently often happens).
=> Fix MANIFEST issues

{{cookiecutter.package_name}}/docs/requirements.txt, {{cookiecutter.package_name}}/docs/source/conf.py
Before submitting a pull request (PR), please read the [contributing guide](https://github.com/neuroinformatics-unit/.github/blob/main/CONTRIBUTING.md).
Google is not indexing the default websites correctly. Generating a sitemap will provide google with all available url paths.
Adds the sphinx-sitemap package to auto-generate a sitemap on build.
#84 
Code tested by building locally and inspecting the sitemap by eye.
No
No
=> Added the sphinx-sitemap package to generate a xml sitemap for google

.github/workflows/test.yml, pyproject.toml
We'd like to move to supporting python 3.11.
Drops Python 3.8 and adds 3.11 instead in `pyproject.toml` and GH actions workflow.
Closes #38 
Checks in CI and locally on my Silicon Mac.
If you're using 3.8, yes.
It's already documented that we follow NEP 29, so no.
=> drop 3.8 support, add 3.11

tests/test_cookiecutter.py, {{cookiecutter.package_name}}/.github/workflows/test_and_deploy.yml, {{cookiecutter.package_name}}/pyproject.toml
#88 only moved to NEP 29 for this repo, and was missing updates to template itself.
Closes #38 
Luckily, we already had a good test, so
* when I updated the template pyproject but not the test, the [CI failed as expected](https://github.com/neuroinformatics-unit/python-cookiecutter/actions/runs/6812410743/job/18524701589?pr=89)
```bash
E       AssertionError: assert '>=3.9.0' == '>=3.8.0'
E         - >=3.8.0
E         ?     ^
E         + >=3.9.0
E         ?     ^
```
* when I also updated the test in line with NEP 3.9,[ the CI passed again](https://github.com/neuroinformatics-unit/python-cookiecutter/actions/runs/6812436645?pr=89)
NA
No
- [NA] The code has been tested locally
- [NA] The documentation has been updated …
=> drop 3.8, add 3.11 in template pyproject

{{cookiecutter.package_name}}/pyproject.toml
We don't want to have `cibuildwheel` by default.
Removes options for `cibuildwheel` from `pyproject.toml`
Closes #81, depends on #89
Searched all files for occurrences of `cibuildwheel` and removed. Existing tests pass. Not sure how to easily do more than that?
In theory, yes, if projects that need cibuildwheel rely on this being here?
AFAICT `cibuildwheel` was not documented here anyway, so no.
- [NA] The code has been tested locally
- [NA] Tests have been added to cover all new functionality
- [NA] The documentation has been updated to reflect any changes
=> Remove `cibuildwheel`

.github/workflows/README.md, .github/workflows/test.yml
We'd like to run our tests regularly, because we rarely make changes to the repo, so we are unlikely to catch dependencies going out of date.
Adds a GH workflow that triggers the test workflow weekly on Sunday at 3AM only on this repo (not on its forks) and on the `main` branch.
Closes #55 
Unfortunately, [newly created scheduled runs are triggered only on the default branch](https://devopsjournal.io/blog/2022/08/12/workflows-not-starting) (for security reasons), so this is difficult to test. I suggest to merge this today and check on Monday whether it was successful?
The changes are based on the [nightly build of libsbml](https://github.com/sbmlteam/libsbml/blob/development/.github/workflows/store-artefact.yml) …
=> Run CI weekly on `main` 

.github/workflows/codespell.yml, .pre-commit-config.yaml, README.md, pyproject.toml, {{cookiecutter.package_name}}/docs/source/index.rst
Fix and prevent future common typos using https://github.com/codespell-project/codespell
Let me know if you want to add support for codespell into the template
Typos are there and more might sneak in
adds pre-commit and github workflow (let me know if I should remove) and fixes some typos
=> Add codespell to test contributed here materials against typos, and fix some typos

.pre-commit-config.yaml, {{cookiecutter.package_name}}/.pre-commit-config.yaml
Updates the pre-commit versions in the template as well as the repo. 
Doesn't close, but further illustrates the need for #95
=> Update pre-commit versions

{{cookiecutter.package_name}}/pyproject.toml
=> Pytest fail when warnings are raised

pyproject.toml, {{cookiecutter.package_name}}/pyproject.toml
This stops ruff from complaining:
> warning: The top-level linter settings are deprecated in favour of their counterparts in the lint section. Please update the following options in pyproject.toml:
>
> - 'select' -> 'lint.select'
=> Replaced select with lint.select in ruff config

.pre-commit-config.yaml, README.md, pyproject.toml, tests/test_cookiecutter.py, {{cookiecutter.package_name}}/.pre-commit-config.yaml, {{cookiecutter.package_name}}/pyproject.toml
- Remove `black` dependency and any related configs from `pyproject.toml` and `pre-commit-config.yaml`
- Use `ruff-format` instead, and configure it in `pyproject.toml` and `pre-commit-config.yaml`
- Update README accordingly
- Add some commented out ruff rules in  the `pyproject.toml` that can be optionally enabled.
=> Replace black with ruff-format

{{cookiecutter.package_name}}/.pre-commit-config.yaml
Follows on from https://github.com/neuroinformatics-unit/python-cookiecutter/pull/121, but updates the version inside the built package.
=> Update .pre-commit-config.yaml inside package

{{cookiecutter.package_name}}/.pre-commit-config.yaml
To update the versions in the pre-commit file inside the package.
It updates the precommit config in the package. Specifically:
-  ruff precommit following PR #127
- `pre-commit-hooks` (version was outdated)
- `mypy` and `check-manifest` hooks, which don't get updated automatically.
PR #127 
It would be nice to automate this as mentioned in #95 - ARC python cookiecutter seems to be using Renovate for this (see example [here](https://github.com/UCL-ARC/python-tooling/pull/485/files)). Will add this info to the issue.
=> Update precommit config inside package

{{cookiecutter.package_name}}/.pre-commit-config.yaml
With Python 3.12, `pre-commit run check-manifest` returns an error of missing dependencies.
According to [this issue](https://github.com/mgedmin/check-manifest/issues/168) this is due to a change in behaviour in Python 3.12, in which apparently `wheel` is no longer preinstalled with virtualenv / venv. See [release notes](https://docs.python.org/3/whatsnew/3.12.html#ensurepip) too.
Option 1: adding `wheel` as an additional dependency in `.pre-commit-config.yaml`. This is implemented in this PR.
```python
- repo: https://github.com/mgedmin/check-manifest
rev: "0.49"
hooks:
- id: check-manifest
args: [--no-build-isolation]
additional_dependencies: [setuptools-scm, wheel]
```
Option 2: specifying a language version for Python in `check-manifest`. Feels less flexible.
```python
- repo: …
```
=> Add wheel as dependency to check-manifest

.github/workflows/docs_build_and _deploy.yml
Before submitting a pull request (PR), please read the [contributing guide](https://github.com/neuroinformatics-unit/.github/blob/main/CONTRIBUTING.md).
Please fill out as much of this template as you can, but if you have any problems or questions, just leave a comment and we will help out :)
Updating workflow to Deploy on: main branch pushes OR tags OR manual trigger
To  Deploy on: main branch pushes OR tags OR manual trigger
#138 
Please explain how any new code has been tested, and how you have ensured that no existing functionality has changed.
No localhost  test 
No
If this PR breaks any existing functionality, please explain how and why.
No
No 
If any features have changed, or have been added. Please explain …
=> Deploy on: main branch pushes OR tags OR manual trigger

tests/test_cookiecutter.py, {{cookiecutter.package_name}}/pyproject.toml
Before submitting a pull request (PR), please read the [contributing guide](https://github.com/neuroinformatics-unit/.github/blob/main/CONTRIBUTING.md).
Please fill out as much of this template as you can, but if you have any problems or questions, just leave a comment and we will help out :)
setuptools>=64: Addresses the editable install issue by setting the lower bound to v64
updates setup tools version 
#136 
Please explain how any new code has been tested, and how you have ensured that no existing functionality has changed.
If this PR breaks any existing functionality, please explain how and why.
If any features have changed, or have been added. Please explain how the
documentation has been updated.
=> Pin setuptools lower bound to >v64

docs/requirements.txt, docs/source/_static/css/custom.css, docs/source/conf.py, docs/source/contributing.md, pyproject.toml, {{cookiecutter.package_name}}/docs/requirements.txt, {{cookiecutter.package_name}}/docs/source/conf.py
Before submitting a pull request (PR), please read the [contributing guide](https://github.com/neuroinformatics-unit/.github/blob/main/CONTRIBUTING.md).
Please fill out as much of this template as you can, but if you have any problems or questions, just leave a comment and we will help out :)
This PR updates the documentation configuration (`docs/source/conf.py`) to retrieve the version using `importlib.metadata.version`.
This change aligns with the recommended usage from [setuptools-scm documentation](https://setuptools-scm.readthedocs.io/en/latest/usage/) for retrieving the version. It replaces the direct call to setuptools_scm.get_version with importlib.metadata.
This PR replaces the `setuptools_scm `version …
=> Use importlib.metadata for package version retrieval in docs
